version: '3'

services:
  app:
    container_name: go-dock
    build: .
    ports:
      - 3000:3000
    restart: on-failure
    environment:
      DB_HOST: db
      DB_USER: test
      DB_PASSWORD: test
      DB_NAME: db
      DB_CONN: "db://test:test@db:5432/db?sslmode=disable"
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    container_name: go-dock-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "db"
      TZ: 'UTC'
      PGTZ: 'UTC'
