// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ramseyjiang/go_mid_to_senior/patterns/dependencyinjection/foobarbaz"
	"github.com/ramseyjiang/go_mid_to_senior/patterns/dependencyinjection/greeter"
	"github.com/ramseyjiang/go_mid_to_senior/patterns/dependencyinjection/shapes"
)

// Injectors from wire.go:

func InitializeEvent() (greeter.Event, error) {
	event, err := greeter.ProvideEvent()
	if err != nil {
		return greeter.Event{}, err
	}
	return event, nil
}

func InitializeBaz() (foobarbaz.Baz, error) {
	foo := foobarbaz.ProvideFoo()
	bar := foobarbaz.ProvideBar(foo)
	baz, err := foobarbaz.ProvideBaz(bar)
	if err != nil {
		return foobarbaz.Baz{}, err
	}
	return baz, nil
}

func ProvideShape() float64 {
	square := shapes.ProvideSquare()
	float64_2 := shapes.ProvideArea(square)
	return float64_2
}
