// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package shapes

import (
	"github.com/google/wire"
)

// Injectors from providers.go:

func ProvideShape() float64 {
	square := ProvideSquare()
	float64_2 := ProvideArea(square)
	return float64_2
}

// providers.go:

func ProvideSquare() *Square {
	sq := Square{4}
	return &sq
}

var ShapeSet = wire.NewSet(
	ProvideSquare, wire.Bind(new(Geometry), new(*Square)),
)

func ProvideArea(g Geometry) float64 {
	return g.Area()
}
