// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: proto/clientstream.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordCallHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *RecordCallHistoryRequest) Reset() {
	*x = RecordCallHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_clientstream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordCallHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordCallHistoryRequest) ProtoMessage() {}

func (x *RecordCallHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientstream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordCallHistoryRequest.ProtoReflect.Descriptor instead.
func (*RecordCallHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientstream_proto_rawDescGZIP(), []int{0}
}

func (x *RecordCallHistoryRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type RecordCallHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallCount    int32 `protobuf:"varint,1,opt,name=callCount,proto3" json:"callCount,omitempty"`
	DurationCall int32 `protobuf:"varint,2,opt,name=durationCall,proto3" json:"durationCall,omitempty"`
}

func (x *RecordCallHistoryResponse) Reset() {
	*x = RecordCallHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_clientstream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordCallHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordCallHistoryResponse) ProtoMessage() {}

func (x *RecordCallHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientstream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordCallHistoryResponse.ProtoReflect.Descriptor instead.
func (*RecordCallHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientstream_proto_rawDescGZIP(), []int{1}
}

func (x *RecordCallHistoryResponse) GetCallCount() int32 {
	if x != nil {
		return x.CallCount
	}
	return 0
}

func (x *RecordCallHistoryResponse) GetDurationCall() int32 {
	if x != nil {
		return x.DurationCall
	}
	return 0
}

var File_proto_clientstream_proto protoreflect.FileDescriptor

var file_proto_clientstream_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x32,
	0x0a, 0x18, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0x5d, 0x0a, 0x19, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x61, 0x6c, 0x6c,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a,
	0x0c, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x6c,
	0x6c, 0x32, 0x5d, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x54, 0x0a, 0x11, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12,
	0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01,
	0x42, 0x1d, 0x5a, 0x1b, 0x61, 0x6c, 0x6c, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_clientstream_proto_rawDescOnce sync.Once
	file_proto_clientstream_proto_rawDescData = file_proto_clientstream_proto_rawDesc
)

func file_proto_clientstream_proto_rawDescGZIP() []byte {
	file_proto_clientstream_proto_rawDescOnce.Do(func() {
		file_proto_clientstream_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_clientstream_proto_rawDescData)
	})
	return file_proto_clientstream_proto_rawDescData
}

var file_proto_clientstream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_clientstream_proto_goTypes = []interface{}{
	(*RecordCallHistoryRequest)(nil),  // 0: pb.RecordCallHistoryRequest
	(*RecordCallHistoryResponse)(nil), // 1: pb.RecordCallHistoryResponse
}
var file_proto_clientstream_proto_depIdxs = []int32{
	0, // 0: pb.Phone.RecordCallHistory:input_type -> pb.RecordCallHistoryRequest
	1, // 1: pb.Phone.RecordCallHistory:output_type -> pb.RecordCallHistoryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_clientstream_proto_init() }
func file_proto_clientstream_proto_init() {
	if File_proto_clientstream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_clientstream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordCallHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_clientstream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordCallHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_clientstream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_clientstream_proto_goTypes,
		DependencyIndexes: file_proto_clientstream_proto_depIdxs,
		MessageInfos:      file_proto_clientstream_proto_msgTypes,
	}.Build()
	File_proto_clientstream_proto = out.File
	file_proto_clientstream_proto_rawDesc = nil
	file_proto_clientstream_proto_goTypes = nil
	file_proto_clientstream_proto_depIdxs = nil
}
