// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: proto/clientstream.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PhoneClient is the client API for Phone service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PhoneClient interface {
	// client stream RPC
	NumCheck(ctx context.Context, opts ...grpc.CallOption) (Phone_NumCheckClient, error)
}

type phoneClient struct {
	cc grpc.ClientConnInterface
}

func NewPhoneClient(cc grpc.ClientConnInterface) PhoneClient {
	return &phoneClient{cc}
}

func (c *phoneClient) NumCheck(ctx context.Context, opts ...grpc.CallOption) (Phone_NumCheckClient, error) {
	stream, err := c.cc.NewStream(ctx, &Phone_ServiceDesc.Streams[0], "/pb.Phone/NumCheck", opts...)
	if err != nil {
		return nil, err
	}
	x := &phoneNumCheckClient{stream}
	return x, nil
}

type Phone_NumCheckClient interface {
	Send(*NumCheckRequest) error
	CloseAndRecv() (*NumCheckResponse, error)
	grpc.ClientStream
}

type phoneNumCheckClient struct {
	grpc.ClientStream
}

func (x *phoneNumCheckClient) Send(m *NumCheckRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *phoneNumCheckClient) CloseAndRecv() (*NumCheckResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(NumCheckResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PhoneServer is the server API for Phone service.
// All implementations should embed UnimplementedPhoneServer
// for forward compatibility
type PhoneServer interface {
	// client stream RPC
	NumCheck(Phone_NumCheckServer) error
}

// UnimplementedPhoneServer should be embedded to have forward compatible implementations.
type UnimplementedPhoneServer struct {
}

func (UnimplementedPhoneServer) NumCheck(Phone_NumCheckServer) error {
	return status.Errorf(codes.Unimplemented, "method NumCheck not implemented")
}

// UnsafePhoneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PhoneServer will
// result in compilation errors.
type UnsafePhoneServer interface {
	mustEmbedUnimplementedPhoneServer()
}

func RegisterPhoneServer(s grpc.ServiceRegistrar, srv PhoneServer) {
	s.RegisterService(&Phone_ServiceDesc, srv)
}

func _Phone_NumCheck_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PhoneServer).NumCheck(&phoneNumCheckServer{stream})
}

type Phone_NumCheckServer interface {
	SendAndClose(*NumCheckResponse) error
	Recv() (*NumCheckRequest, error)
	grpc.ServerStream
}

type phoneNumCheckServer struct {
	grpc.ServerStream
}

func (x *phoneNumCheckServer) SendAndClose(m *NumCheckResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *phoneNumCheckServer) Recv() (*NumCheckRequest, error) {
	m := new(NumCheckRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Phone_ServiceDesc is the grpc.ServiceDesc for Phone service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Phone_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Phone",
	HandlerType: (*PhoneServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "NumCheck",
			Handler:       _Phone_NumCheck_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/clientstream.proto",
}
