// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: proto/serverstream.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PhoneClient is the client API for Phone service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PhoneClient interface {
	AllContacts(ctx context.Context, in *AllContactsRequest, opts ...grpc.CallOption) (Phone_AllContactsClient, error)
	PageContacts(ctx context.Context, in *PageContactsRequest, opts ...grpc.CallOption) (Phone_PageContactsClient, error)
}

type phoneClient struct {
	cc grpc.ClientConnInterface
}

func NewPhoneClient(cc grpc.ClientConnInterface) PhoneClient {
	return &phoneClient{cc}
}

func (c *phoneClient) AllContacts(ctx context.Context, in *AllContactsRequest, opts ...grpc.CallOption) (Phone_AllContactsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Phone_ServiceDesc.Streams[0], "/pb.Phone/AllContacts", opts...)
	if err != nil {
		return nil, err
	}
	x := &phoneAllContactsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Phone_AllContactsClient interface {
	Recv() (*AllContactsResponse, error)
	grpc.ClientStream
}

type phoneAllContactsClient struct {
	grpc.ClientStream
}

func (x *phoneAllContactsClient) Recv() (*AllContactsResponse, error) {
	m := new(AllContactsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *phoneClient) PageContacts(ctx context.Context, in *PageContactsRequest, opts ...grpc.CallOption) (Phone_PageContactsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Phone_ServiceDesc.Streams[1], "/pb.Phone/PageContacts", opts...)
	if err != nil {
		return nil, err
	}
	x := &phonePageContactsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Phone_PageContactsClient interface {
	Recv() (*PageContactsResponse, error)
	grpc.ClientStream
}

type phonePageContactsClient struct {
	grpc.ClientStream
}

func (x *phonePageContactsClient) Recv() (*PageContactsResponse, error) {
	m := new(PageContactsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PhoneServer is the server API for Phone service.
// All implementations should embed UnimplementedPhoneServer
// for forward compatibility
type PhoneServer interface {
	AllContacts(*AllContactsRequest, Phone_AllContactsServer) error
	PageContacts(*PageContactsRequest, Phone_PageContactsServer) error
}

// UnimplementedPhoneServer should be embedded to have forward compatible implementations.
type UnimplementedPhoneServer struct {
}

func (UnimplementedPhoneServer) AllContacts(*AllContactsRequest, Phone_AllContactsServer) error {
	return status.Errorf(codes.Unimplemented, "method AllContacts not implemented")
}
func (UnimplementedPhoneServer) PageContacts(*PageContactsRequest, Phone_PageContactsServer) error {
	return status.Errorf(codes.Unimplemented, "method PageContacts not implemented")
}

// UnsafePhoneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PhoneServer will
// result in compilation errors.
type UnsafePhoneServer interface {
	mustEmbedUnimplementedPhoneServer()
}

func RegisterPhoneServer(s grpc.ServiceRegistrar, srv PhoneServer) {
	s.RegisterService(&Phone_ServiceDesc, srv)
}

func _Phone_AllContacts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AllContactsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PhoneServer).AllContacts(m, &phoneAllContactsServer{stream})
}

type Phone_AllContactsServer interface {
	Send(*AllContactsResponse) error
	grpc.ServerStream
}

type phoneAllContactsServer struct {
	grpc.ServerStream
}

func (x *phoneAllContactsServer) Send(m *AllContactsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Phone_PageContacts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PageContactsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PhoneServer).PageContacts(m, &phonePageContactsServer{stream})
}

type Phone_PageContactsServer interface {
	Send(*PageContactsResponse) error
	grpc.ServerStream
}

type phonePageContactsServer struct {
	grpc.ServerStream
}

func (x *phonePageContactsServer) Send(m *PageContactsResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Phone_ServiceDesc is the grpc.ServiceDesc for Phone service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Phone_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Phone",
	HandlerType: (*PhoneServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AllContacts",
			Handler:       _Phone_AllContacts_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PageContacts",
			Handler:       _Phone_PageContacts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/serverstream.proto",
}
