// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: proto/serverstream.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PhoneClient is the client API for Phone service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PhoneClient interface {
	// server stream RPC
	ListContacts(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (Phone_ListContactsClient, error)
}

type phoneClient struct {
	cc grpc.ClientConnInterface
}

func NewPhoneClient(cc grpc.ClientConnInterface) PhoneClient {
	return &phoneClient{cc}
}

func (c *phoneClient) ListContacts(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (Phone_ListContactsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Phone_ServiceDesc.Streams[0], "/pb.Phone/ListContacts", opts...)
	if err != nil {
		return nil, err
	}
	x := &phoneListContactsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Phone_ListContactsClient interface {
	Recv() (*ListContactsResponse, error)
	grpc.ClientStream
}

type phoneListContactsClient struct {
	grpc.ClientStream
}

func (x *phoneListContactsClient) Recv() (*ListContactsResponse, error) {
	m := new(ListContactsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PhoneServer is the server API for Phone service.
// All implementations should embed UnimplementedPhoneServer
// for forward compatibility
type PhoneServer interface {
	// server stream RPC
	ListContacts(*ListContactsRequest, Phone_ListContactsServer) error
}

// UnimplementedPhoneServer should be embedded to have forward compatible implementations.
type UnimplementedPhoneServer struct {
}

func (UnimplementedPhoneServer) ListContacts(*ListContactsRequest, Phone_ListContactsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListContacts not implemented")
}

// UnsafePhoneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PhoneServer will
// result in compilation errors.
type UnsafePhoneServer interface {
	mustEmbedUnimplementedPhoneServer()
}

func RegisterPhoneServer(s grpc.ServiceRegistrar, srv PhoneServer) {
	s.RegisterService(&Phone_ServiceDesc, srv)
}

func _Phone_ListContacts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListContactsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PhoneServer).ListContacts(m, &phoneListContactsServer{stream})
}

type Phone_ListContactsServer interface {
	Send(*ListContactsResponse) error
	grpc.ServerStream
}

type phoneListContactsServer struct {
	grpc.ServerStream
}

func (x *phoneListContactsServer) Send(m *ListContactsResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Phone_ServiceDesc is the grpc.ServiceDesc for Phone service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Phone_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Phone",
	HandlerType: (*PhoneServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListContacts",
			Handler:       _Phone_ListContacts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/serverstream.proto",
}
