build:
	mkdir -p gopatterns
	cd gopatterns && mkdir -p creational
	cd gopatterns && mkdir -p structural
	cd gopatterns && mkdir -p behaviour
	cd gopatterns && mkdir -p concurrency
	cd gopatterns && mkdir -p microservice
